###
POST http://localhost:5000/posts
Content-Type: application/json

{
    "title":"title one",
    "body":"body one"
}


###
GET http://localhost:5000/users

###
PUT http://localhost:5000/2
Content-Type: application/json

{
    "age":"6",
    "nationality":"ugandan"
}