###
POST http://localhost:5000/posts
Content-Type: application/json

{
    "title":"title two",
    "body":"body two"
}


###
GET http://localhost:5000/users

###
PUT http://localhost:5000/56b7d524-3887-4807-9b4a-5e5425039ae0
Content-Type: application/json

{
    "body":"body updated",
    "title":"title two"
}