###
POST http://localhost:5000/users
Content-Type: application/json

{
    "firstname":"said",
    "lastname":"maulid",
    "nationality":"kenyan",
    "age":"20"

}


###
GET http://localhost:5000/users

###
PUT http://localhost:5000/2
Content-Type: application/json

{
    "age":"6",
    "nationality":"ugandan"
}